spring.application.name=FuegoYPanTFG
server.port=8081

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/fuegoypan
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#twilio
twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.whatsapp.from=whatsapp:+14155238886
twilio.whatsapp.to=whatsapp:+34640995296

