# Aplicaci�n
spring.application.name=FuegoYPanTFG
server.port=8081

# Configuraci�n de MariaDB Cloud (SkySQL)
spring.datasource.url=jdbc:mariadb://serverless-europe-west3.sysp0000.db2.skysql.com:4068/FuegoyPan?requireSSL=true&useSSL=true
spring.datasource.username=dbpgf14695271
spring.datasource.password=tLlTOXnUs2SFtWgV30q8V]Rh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#twilio
twilio.account.sid=ACddd15e4739da42ea0c76f72b497f29da
twilio.auth.token=29ab523e0de613969ea52728f55e1d51
twilio.whatsapp.from=whatsapp:+14155238886
twilio.whatsapp.to=whatsapp:+34640995296

#Srtipe
stripe.secret.key=sk_test_51TTI7fAJGNoa6k3KMY041I0xb78DVNWRD8mZjoHIQ5x4o2268KDVkO2lLFo04ZlgdbhClipDja3zmPqadsbFCxHN00iu4DrKuk
stripe.webhook.secret=whsec_5871bd56ee208c1fb8175c9f5ee5f4a7e3f79e4541343b7205e7bc9be45e94d9