# Aplicación
spring.application.name=FuegoYPanTFG
server.port=8081

# Configuración de MariaDB Cloud (SkySQL)
spring.datasource.url=jdbc:mariadb://serverless-europe-west3.sysp0000.db2.skysql.com:4068/FuegoyPan?requireSSL=true&useSSL=true
spring.datasource.username=dbpgf14695271
spring.datasource.password=tLlTOXnUs2SFtWgV30q8V]Rh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Opciones de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

